services:
  db:
    image: postgres:18
    container_name: demetra-homework-1-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?set POSTGRES_USER in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:?set POSTGRES_DB in .env}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST:?set POSTGRES_DB_TEST in .env}
    ports:
      - '${POSTGRES_PORT:?set POSTGRES_PORT in .env}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db.sh:/docker-entrypoint-initdb.d/01-init-db.sh:ro

volumes:
  postgres_data:
